#!/bin/zsh

__fzf::widget::init || return 1

__fzf::widget::widgets 'fzf-podman-' | sed 's/fzf-//' | \
  __fzf::widget::select $FZF_WIDGET_OPTS[select-podman-widget] +m | \
  sed 's/^/fzf-/' | \
  __fzf::widget::exec -q
