#!/bin/zsh

__fzf::widget::init 'cd --' || return 1

eval "${FZF_CHANGE_DIR_FIND_COMMAND:-"find . -mindepth 1 \\( -type d -o -type l \\) \\
  -printf '%P\n' 2>/dev/null"}" | \
  __fzf::widget::select $FZF_WIDGET_OPTS[change-dir] +m | \
  __fzf::widget::insert -q

__fzf::widget::exec
