#!/bin/zsh

__fzf::widget::init 'podman container rm' || return 1

podman container list --all --format "table {{.ID}} {{.Names}} {{.Command}} {{.Status}}" | \
  __fzf::widget::select $FZF_WIDGET_OPTS[podman-remove-containers] -m | \
  awk '{print $1}' | \
  __fzf::widget::insert

__fzf::widget::exec
