#!/bin/zsh

if ! __fzf::widget::check 'dnf'; then
  __fzf::widget::print 'fzf-dnf-install: commnad not found: dnf'
  return 1
fi

__fzf::widget::init "sudo dnf install" || return 1

dnf --cacheonly --quiet list --available | cut -d' ' -f1 | \
  __fzf::widget::select $FZF_WIDGET_OPTS[dnf-remove] -m --header-lines=1 | \
  __fzf::widget::insert -q

__fzf::widget::exec
