#!/bin/zsh

__fzf::widget::init 'docker container logs' || return 1

docker container ls -a | \
  __fzf::widget::select $FZF_WIDGET_OPTS[docker-logs-container] +m --header-lines=1 | \
  awk '{print $1}' | \
  __fzf::widget::insert

__fzf::widget::exec
