#!/bin/zsh

__fzf::widget::init 'docker image rm' || return 1

docker image ls | \
  __fzf::widget::select $FZF_WIDGET_OPTS[docker-remove-images] -m --header-lines=1 | \
  awk '{print $3}' | \
  __fzf::widget::insert

__fzf::widget::exec
