#!/bin/zsh

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  __fzf::widget::print 'fzf-github-reopen-issue: Not a git repository'
  return 1
fi

if ! __fzf::widget::check 'gh'; then
  local msg='fzf-github-reopen-issue: commnad not found: gh

  Please install gh (https://github.com/cli/cli).
  '
  __fzf::widget::print "$msg"
  return 1
fi

__fzf::widget::init 'gh issue reopen' || return 1

(
  gh issue list --state closed --limit 100
) | __fzf::widget::select $FZF_WIDGET_OPTS[github-open-issue] +m | \
  awk '{print $1}' | \
  __fzf::widget::insert -q

__fzf::widget::exec
