#!/bin/zsh

__fzf::widget::init 'docker container stop' || return 1

docker container ls | \
  __fzf::widget::select $FZF_WIDGET_OPTS[docker-stop-containers] -m --header-lines=1 | \
  awk '{print $1}' | \
  __fzf::widget::insert

__fzf::widget::exec
