#!/bin/zsh

__fzf::widget::init "$EDITOR --" || return 1

cat "${FZF_EDIT_DOTFILES_FILE:-$HOME/.dotfiles}" | \
  __fzf::widget::select $FZF_WIDGET_OPTS[edit-dotfiles] -m | \
  __fzf::widget::insert -q

__fzf::widget::exec
