#!/bin/zsh

__fzf::widget::init 'cd --' || return 1

find "$HOME"/*(/) -maxdepth 3 -type d -name '.git' -printf '%h\n' | \
  sed "s|$HOME|~|g" | \
  __fzf::widget::select $FZF_WIDGET_OPTS[change-repository] +m | \
  __fzf::widget::insert -q

__fzf::widget::exec
