#!/bin/zsh

__fzf::widget::init || return 1

eval "${FZF_INSERT_DIR_FIND_COMMAND:-"find -L . \\( -type d -o -type l \\) -printf '%P\\n' \\
  -o \\( -path '*/\\.*' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \\) \\
  -prune 2>/dev/null"}" | \
  __fzf::widget::select $FZF_WIDGET_OPTS[insert-directory] +m | \
  __fzf::widget::insert -q
