#!/bin/zsh

__fzf::widget::init 'podman pod rm' || return 1

podman pod ps --format "table {{.Id}} {{.Name}} {{.NumberOfContainers}} {{.Status}}" | \
  __fzf::widget::select $FZF_WIDGET_OPTS[podman-stop-containers] -m --header-lines=1 | \
  awk '{print $1}' | \
  __fzf::widget::insert

__fzf::widget::exec
