#!/bin/zsh

__fzf::widget::init || return 1

__fzf::widget::widgets | sed -e '/fzf-select.*-widget/d' -e 's/fzf-//' | \
  __fzf::widget::select $FZF_WIDGET_OPTS[select-widget] +m | \
  sed 's/^/fzf-/' | \
  __fzf::widget::exec -q
