#!/bin/zsh

__fzf::widget::init 'docker volume rm' || return 1

docker volume ls | \
  __fzf::widget::select $FZF_WIDGET_OPTS[docker-remove-volumes] -m --header-lines=1 | \
  awk '{print $2}' | \
  __fzf::widget::insert

__fzf::widget::exec
