#!/bin/zsh

__fzf::widget::init 'ssh --' || return 1

awk '($1 ~ "^[Hh]ost$") && (!/\*/) {
        if (length($2) > 0) { print $2 | "sort -u" }
    }' ~/.ssh/config /etc/ssh/ssh_config 2>/dev/null | \
  __fzf::widget::select $FZF_WIDGET_OPTS[exec-ssh] +m | \
  __fzf::widget::insert

__fzf::widget::exec
