#!/bin/zsh

__fzf::widget::init "$EDITOR --" || return 1

eval "${FZF_EDIT_FILES_COMMAND:-"find -L . \\( -type f -o -type l \\) -printf '%P\n' \\
  -o \\( -path '*/\\.*' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \\) \\
  -prune 2>/dev/null"}" | \
  __fzf::widget::select $FZF_WIDGET_OPTS[edit-files] -m | \
  __fzf::widget::insert -q

__fzf::widget::exec
